### ISSUE TITLE
Why is frequency limited to 1-4 or L?

### ISSUE THREAD

**Issue by Jogai** [ZodmanPerth/Darecali#3]
Regarding https://github.com/ZodmanPerth/Darecali/blob/master/Darecali/Factory.cs#L171

Why is it limited to the first 4? What if I want to have a recurrence every 8th day of the month?

**Comment by ZodmanPerth** [comment]
Great question, thanks for asking!  It's not clear from anywhere in the wiki how to do this.

Let me explain why this before I give you the answer.  If you want the tl;dr jump to the bottom of this post.

_{frequency}_ is only used in certain recurrence strategies.  You can see which ones by looking at the [Recurrence Strategies Section](https://github.com/ZodmanPerth/Darecali/wiki/The-Strategy-Definition-Language#recurrence-strategies) in the wiki.  This is where I attempt to show all the possible combinations of input types used in the Factory.

As you can see from the link, there's only two strategies that take _{frequency}_ values; a monthly one and a yearly one:
- Every {frequency} {day} of every {n} month(s)
- Every {frequency} {day} of every specified month, every {n} years

The key thing to note is that _{frequency}_ is a modifier for _{day}_.

Looking further down the page at the [Syntax section](https://github.com/ZodmanPerth/Darecali/wiki/The-Strategy-Definition-Language#syntax), it shows how to fully specify these two strategies:

```
Mfrequency,day,n         - Monthly: every frequency day of every n month(s)
                                    where frequency is 1-4 for First-Fourth
                                                    or 'L' for Last
                                          day is 1-7 for Sunday-Saturday
                                              or 'd' for day
                                              or 'wd' for weekday
                                              or 'we' for weekend day
                                          n is a positive integer
```

and 

```
Yfrequency,day,month,n   - Yearly : the frequency day of specified month, every n year(s)
                                    where frequency is 1-4 for First-Fourth
                                                    or 'L' for Last
                                          day is 1-7 for Sunday-Saturday
                                              or 'd' for day
                                              or 'wd' for weekday
                                              or 'we' for weekend day
                                          month is 1-12 for January-December
                                          n is a positive integer
```

So _{frequency}_ modifies a _{day}_ to create recurrences such as:
"Every second Sunday of every 6 month(s)"
or 
"Every last weekday of every July, every 2 years"

Note that _{day}_ is a day of the week, or a special subset of days of the week (weekday or weekend day).  It only makes sense to have values 1-4 or L(ast) to modify a day of the week because there is a maximum of 5 of any day of the week in any month, ever.  

I could have allowed 1-5 and L(ast) as values, but really 5 is the same as L(ast), so I dropped it.

Now to answer your question.  When you want to specify dates such as the 8th day of every Month, there is a different Month strategy you need to use:
- Every {n} month(s) on specified day(s)

In your case you want "Every 1 month(s) on day 8".  

This syntax for this strategy is as follows:

```
M[day[,n]]               - Monthly: every n month(s) on specified day
                                    where day is an integer 1-31 (default is 1)
                                          n is a positive integer (default is 1)
```

So for your example you want the specified day to be 8 and _n_ to be 1 (or not specified at all).  If you're using the Strategy Definition Language you would specify this as "M8,1" or simply "M8".

The example for this stategy is [here on the samples page](https://github.com/ZodmanPerth/Darecali/wiki/Samples#recur-every-n-months-on-specified-days).

I recognise that without clearer examples, figuring out which strategy to use for recurrence patterns is tricky.  I hope that I can clear up these points of confusion over time as people ask questions.

I also recognise the term "frequency" may be misleading here.  Believe me, I agonised over what to call these things, but "frequency" was the most appropriate term I could come up with.

Hopefully that clears up the confusion for you.  If you have any suggestions for making it clearer I would really appreciate the feedback.

**Comment by Jogai** [comment]
Thanks for clearing that up. The syntax confused me indeed.

Regarding syntax:
There is:
- Mfrequency,day,n 
- Yfrequency,day,month,n

In these cases frequency is a 'modifier' of day, so parameter 1 'modifies' 2.
Parameter n is a 'modifier' of frequency, so the last parameter 'modifies'  parameter 0.

Maybe a FAQ page with this info would help?
